//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clicker.DataSection
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarCodeData
    {
        public BarCodeData()
        {
            this.ImagesHistories = new HashSet<ImagesHistory>();
            this.FilesINBarCodes = new HashSet<FilesINBarCode>();
        }
    
        public long ID { get; set; }
        public string کلاسه { get; set; }
        public double کد_تفضیلی { get; set; }
        public string نام_موقوفه { get; set; }
        public Nullable<bool> PrintSts { get; set; }
        public string PrintDate { get; set; }
        public Nullable<bool> Lock { get; set; }
    
        public virtual ICollection<ImagesHistory> ImagesHistories { get; set; }
        public virtual ICollection<FilesINBarCode> FilesINBarCodes { get; set; }
    }
}
