//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clicker.DataSection
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesINBarCode
    {
        public long FileId { get; set; }
        public double FK_Barcode { get; set; }
        public int FK_FileClass { get; set; }
        public string FileURL { get; set; }
        public string Filename { get; set; }
        public string ClassificationDateTime { get; set; }
        public Nullable<long> FK_PersonCodeClassification { get; set; }
        public string UploadedDateTime { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> ClassificationDateTime_G { get; set; }
        public Nullable<System.DateTime> UploadedDateTime_G { get; set; }
        public string ReservedFor { get; set; }
        public string ReservedDateTime { get; set; }
        public Nullable<System.DateTime> ReservedDateTime_G { get; set; }
    
        public virtual BarCodeData BarCodeData { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual FileClass FileClass { get; set; }
    }
}
