//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clicker.DataSection
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileClass
    {
        public FileClass()
        {
            this.FilesINBarCodes = new HashSet<FilesINBarCode>();
        }
    
        public int ClassID { get; set; }
        public string FileClassNameEN { get; set; }
        public string FileClassNameFa { get; set; }
        public string CreateDate { get; set; }
    
        public virtual ICollection<FilesINBarCode> FilesINBarCodes { get; set; }
    }
}
