//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clicker.DataSection
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesHistory
    {
        public long HistoryId { get; set; }
        public double FK_barcode { get; set; }
        public string ClassificationDateTime { get; set; }
        public string SuccessfulUploadDateTime { get; set; }
        public string GlobalErrorInUploadDateTime { get; set; }
        public string GlobalErrorInUploadMessage { get; set; }
        public Nullable<System.DateTime> ClassificationDateTime_G { get; set; }
    
        public virtual BarCodeData BarCodeData { get; set; }
    }
}
