//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clicker.DataSection
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTracking
    {
        public long LogId { get; set; }
        public System.Guid FkUserId { get; set; }
        public string LogDateTime { get; set; }
        public string LogEventName { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
